// SOURCE_COLORS is loaded from /colors.js (generated by crawler.py)

const AD_EVERY = 25; // insert an ad slot after every N visible articles
const EXT_SVG =
  '<svg class="ext" viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 17L17 7M9 7h8v8"/></svg>';

function fmtTime(s) {
  if (!s) return "";
  const d = new Date(s);
  if (isNaN(d)) return "";
  // Swiss local HH:MM (mirrors fmt_time in crawler.py)
  return d.toLocaleString("de-CH", {
    timeZone: "Europe/Zurich",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function ts(a) {
  const d = new Date(a.published);
  return isNaN(d) ? 0 : d.getTime();
}

// Preferred source order; listed sources rank first (in this order), rest after.
// Prioritize sources with fewer updates for fairer visibility.
const SOURCE_PRIORITY = [
  "Inside Paradeplatz",
  "Infosperber",
  "Rathuus",
  "Inside IT",
  "Nebelspalter",
  "Bilanz",
  "Republik",
  "Weltwoche",
  "NZZ",
];
function prio(a) {
  const i = SOURCE_PRIORITY.indexOf(a.source);
  return i === -1 ? SOURCE_PRIORITY.length : i;
}

function sortArticles(articles, mode) {
  const out = articles.slice();
  if (mode === "source") {
    out.sort((a, b) => a.source.localeCompare(b.source) || ts(b) - ts(a));
  } else {
    out.sort((a, b) => ts(b) - ts(a) || prio(a) - prio(b));
  }
  return out;
}

// Excluded sources (lowercased), persisted in the URL: ?exclude=blick,watson
const excluded = new Set(
  (new URLSearchParams(location.search).get("exclude") || "")
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
);

function isExcluded(a) {
  return excluded.has(a.source.toLowerCase());
}

// Free-text search over title + source, persisted in the URL: ?q=…
let query = (new URLSearchParams(location.search).get("q") || "").trim().toLowerCase();

function matchesQuery(a) {
  if (!query) return true;
  return a.title.toLowerCase().includes(query) ||
         a.source.toLowerCase().includes(query);
}

function syncUrl() {
  const params = new URLSearchParams(location.search);
  if (excluded.size) params.set("exclude", [...excluded].join(","));
  else params.delete("exclude");
  if (query) params.set("q", query);
  else params.delete("q");
  const qs = params.toString();
  history.replaceState(null, "", location.pathname + (qs ? "?" + qs : ""));
}

function articleNode(a) {
  const li = document.createElement("li");
  li.className = "article";

  const metaCol = document.createElement("div");
  metaCol.className = "meta-col";

  const src = document.createElement("span");
  src.className = "source";
  src.textContent = a.source;
  src.style.background = SOURCE_COLORS[a.source] || "#888";
  metaCol.appendChild(src);

  const time = document.createElement("span");
  time.className = "time";
  time.innerHTML = `${fmtTime(a.published)} ${EXT_SVG}`;
  metaCol.appendChild(time);

  const link = document.createElement("a");
  link.className = "title";
  link.href = a.url;
  link.textContent = a.title;
  link.target = "_blank";
  link.rel = "noopener";

  li.appendChild(metaCol);
  li.appendChild(link);
  return li;
}

function adNode() {
  const li = document.createElement("li");
  li.className = "ad-slot";
  li.textContent = "Werbung";
  return li;
}

function render(articles, mode) {
  const list = document.getElementById("list");
  if (!list) return;
  list.innerHTML = "";
  const visible = sortArticles(articles, mode)
    .filter((a) => !isExcluded(a) && matchesQuery(a));
  visible.forEach((a, i) => {
    list.appendChild(articleNode(a));
    if ((i + 1) % AD_EVERY === 0 && i + 1 < visible.length) {
      list.appendChild(adNode());
    }
  });
}

function sortMode() {
  const el = document.querySelector('input[name="sort"]:checked');
  return el ? el.value : "date";
}

let current = [];

// "Medias" filter: clickable source toggles, persisted via ?exclude=
function buildFilters(articles) {
  const box = document.getElementById("filters");
  if (!box) return;
  box.innerHTML = "";
  const sources = [...new Set(articles.map((a) => a.source))].sort();
  for (const s of sources) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = s;
    const on = () => !excluded.has(s.toLowerCase());
    btn.setAttribute("aria-pressed", String(on()));
    btn.addEventListener("click", () => {
      if (on()) excluded.add(s.toLowerCase());
      else excluded.delete(s.toLowerCase());
      btn.setAttribute("aria-pressed", String(on()));
      syncUrl();
      render(current, sortMode());
    });
    box.appendChild(btn);
  }
}

function load(url) {
  fetch(url)
    .then((r) => r.json())
    .then((data) => {
      current = data.articles;
      buildFilters(current);
      // Re-render if URL carried a filter/search; otherwise keep the SSR markup.
      if (excluded.size || query) render(current, sortMode());
    })
    .catch(() => {});
}

// ---------- View switching (feed / settings / more) ----------
const feedView = document.getElementById("feedView");
const settingsView = document.getElementById("settingsView");
const moreView = document.getElementById("moreView");
const feedToggle = document.getElementById("feedToggle");
const moreToggle = document.getElementById("moreToggle");

function showView(name) {
  if (feedView) feedView.hidden = name !== "feed";
  if (settingsView) settingsView.hidden = name !== "settings";
  if (moreView) moreView.hidden = name !== "more";
  if (feedToggle) feedToggle.setAttribute("aria-expanded", String(name === "settings"));
  if (moreToggle) moreToggle.setAttribute("aria-expanded", String(name === "more"));
  window.scrollTo(0, 0);
}

if (feedToggle) {
  feedToggle.addEventListener("click", () => {
    showView(settingsView && settingsView.hidden ? "settings" : "feed");
  });
}
if (moreToggle) {
  moreToggle.addEventListener("click", () => {
    showView(moreView && moreView.hidden ? "more" : "feed");
  });
}

// ---------- Mobile accordions for feed-settings groups ----------
const mobile = window.matchMedia("(max-width: 760px)");
for (const head of document.querySelectorAll(".fs-head")) {
  // <details> already toggles; on mobile we collapse via the .open class on the group
  // and suppress the native marker, so intercept and drive the class instead.
  head.addEventListener("click", (e) => {
    if (!mobile.matches) return;
    e.preventDefault();
    head.closest(".fs-group").classList.toggle("open");
  });
}

// ---------- Boot ----------
const dayParam = new URLSearchParams(location.search).get("day");
if (dayParam) {
  // Redirect legacy ?day= URLs to static archive pages
  location.replace(`/archive/${dayParam}.html`);
} else {
  // archive/2026-06-07.html → 2026-06-07.json (sibling); else /crawled.json
  const archiveMatch = location.pathname.match(/\/archive\/(\d{4}-\d{2}-\d{2})\.html$/);
  const jsonUrl = archiveMatch ? `${archiveMatch[1]}.json` : "/crawled.json";
  load(jsonUrl);
}

const searchInput = document.getElementById("search");
if (searchInput) {
  searchInput.value = query;
  searchInput.addEventListener("input", () => {
    query = searchInput.value.trim().toLowerCase();
    syncUrl();
    render(current, sortMode());
  });
}
