// SOURCE_COLORS is loaded from /colors.js (generated by crawler.py)

const AD_EVERY = 25; // insert an ad slot after every N visible articles
const EXT_SVG =
  '<svg class="ext" viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 17L17 7M9 7h8v8"/></svg>';
const OPEN_SVG =
  '<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 17L17 7M9 7h8v8"/></svg>';
const LINK_SVG =
  '<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1"/><path d="M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1"/></svg>';

// Stable per-article anchor id (mirrors article_id() in crawler.py). Used for
// "Artikel teilen" deep-links: https://all.news/#<id>
function slugify(s) {
  return (s || "")
    .toLowerCase()
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/^-+|-+$/g, "");
}
function djb2(s) {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h * 33) + s.charCodeAt(i)) >>> 0;
  return h;
}
function articleId(a) {
  return `${slugify(a.title)}-${djb2(a.url).toString(16)}`;
}

function fmtTime(s) {
  if (!s) return "";
  const d = new Date(s);
  if (isNaN(d)) return "";
  // Swiss local HH:MM (mirrors fmt_time in crawler.py)
  return d.toLocaleString("de-CH", {
    timeZone: "Europe/Zurich",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function ts(a) {
  const d = new Date(a.published);
  return isNaN(d) ? 0 : d.getTime();
}

// Preferred source order; listed sources rank first (in this order), rest after.
// Prioritize sources with fewer updates for fairer visibility.
const SOURCE_PRIORITY = [
  "Inside Paradeplatz",
  "Infosperber",
  "Rathuus",
  "Inside IT",
  "Nebelspalter",
  "Bilanz",
  "Republik",
  "Weltwoche",
  "NZZ",
];
function prio(a) {
  const i = SOURCE_PRIORITY.indexOf(a.source);
  return i === -1 ? SOURCE_PRIORITY.length : i;
}

function sortArticles(articles, mode) {
  const out = articles.slice();
  if (mode === "source") {
    out.sort((a, b) => a.source.localeCompare(b.source) || ts(b) - ts(a));
  } else {
    out.sort((a, b) => ts(b) - ts(a) || prio(a) - prio(b));
  }
  return out;
}

// Excluded sources (lowercased), persisted in the URL: ?exclude=blick,watson
const excluded = new Set(
  (new URLSearchParams(location.search).get("exclude") || "")
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
);
// Included countries (ISO 3166-1 codes, lowercased), persisted as ?country=ch,de.
// INCLUDE model: empty set = show all countries; non-empty = show only those.
// The welcome modal seeds this with the visitor's primary (home) country.
const includedCountries = new Set(
  (new URLSearchParams(location.search).get("country") || "")
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
);
// Included languages (ISO 639-1 codes, lowercased), persisted as ?lang=de,fr.
// INCLUDE model like countries: empty = all languages; non-empty = only those.
const includedLangs = new Set(
  (new URLSearchParams(location.search).get("lang") || "")
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
);
// ISO 3166-1 alpha-2 -> display name. Extend as the source scope widens.
const COUNTRY_NAMES = {
  CH: "Switzerland", DE: "Germany", FR: "France",
  GB: "United Kingdom", US: "United States", IT: "Italy", ES: "Spain",
  NL: "Netherlands", BE: "Belgium", AT: "Austria", PT: "Portugal", IE: "Ireland",
  PL: "Poland", SE: "Sweden", NO: "Norway", DK: "Denmark", FI: "Finland",
  GR: "Greece", CZ: "Czechia", HU: "Hungary", RO: "Romania", UA: "Ukraine", TR: "Turkey",
  CA: "Canada", MX: "Mexico", BR: "Brazil", AR: "Argentina", CO: "Colombia", PE: "Peru",
  AU: "Australia", NZ: "New Zealand",
  IN: "India", JP: "Japan", KR: "South Korea", SG: "Singapore", ID: "Indonesia",
  PH: "Philippines", VN: "Vietnam", PK: "Pakistan", IL: "Israel", QA: "Qatar", HK: "Hong Kong",
};
// ISO 639-1 -> display name (shown in the source's own language).
const LANG_NAMES = {
  de: "Deutsch", fr: "Français", en: "English", it: "Italiano", es: "Español",
  nl: "Nederlands", pt: "Português", pl: "Polski", sv: "Svenska", no: "Norsk",
  da: "Dansk", fi: "Suomi", el: "Ελληνικά", cs: "Čeština", hu: "Magyar", ro: "Română",
  uk: "Українська", tr: "Türkçe", ja: "日本語", id: "Bahasa Indonesia", vi: "Tiếng Việt",
};

function isExcluded(a) {
  const country = (a.country || "").toLowerCase();
  const lang = (a.lang || "").toLowerCase();
  return excluded.has(a.source.toLowerCase()) ||
         (includedCountries.size > 0 && !includedCountries.has(country)) ||
         (includedLangs.size > 0 && !includedLangs.has(lang));
}

// Free-text search over title + source, persisted in the URL: ?q=…
let query = (new URLSearchParams(location.search).get("q") || "").trim().toLowerCase();

function matchesQuery(a) {
  if (!query) return true;
  return a.title.toLowerCase().includes(query) ||
         a.source.toLowerCase().includes(query);
}

function syncUrl() {
  const params = new URLSearchParams(location.search);
  if (excluded.size) params.set("exclude", [...excluded].join(","));
  else params.delete("exclude");
  if (includedCountries.size) params.set("country", [...includedCountries].join(","));
  else params.delete("country");
  if (includedLangs.size) params.set("lang", [...includedLangs].join(","));
  else params.delete("lang");
  if (query) params.set("q", query);
  else params.delete("q");
  const qs = params.toString();
  history.replaceState(null, "", location.pathname + (qs ? "?" + qs : ""));
}

// HTML-escape for text and attribute values (mirrors escape() in crawler.py).
function esc(s) {
  return (s == null ? "" : String(s))
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

// One row as an HTML string (mirrors render_article_html in crawler.py). Building
// the whole list as a single string + one innerHTML assignment is far faster than
// per-node DOM construction; clicks are handled by delegation, so no per-row
// listeners are needed.
function articleHTML(a) {
  const color = SOURCE_COLORS[a.source] || "#888";
  const url = esc(a.url);
  return `<li class="article" id="${esc(articleId(a))}" data-lang="${esc(a.lang || "de")}" data-country="${esc(a.country || "CH")}">` +
    `<div class="meta-col">` +
    `<span class="source" style="background:${color}">${esc(a.source)}</span>` +
    `<span class="time">${esc(fmtTime(a.published))} ${EXT_SVG}</span>` +
    `</div>` +
    `<a class="title" href="${url}" target="_blank" rel="noopener">${esc(a.title)}</a>` +
    `<div class="row-actions">` +
    `<a class="row-act open" href="${url}" target="_blank" rel="noopener"><span class="label">Open</span> ${OPEN_SVG}</a>` +
    `<button class="row-act share" type="button"><span class="label">Share</span> ${LINK_SVG}</button>` +
    `</div></li>`;
}

const AD_SLOT_HTML = '<li class="ad-slot">Werbung</li>';

// Reflect the number of currently-visible articles in the wordmark badge.
function setCountBadge(n) {
  const el = document.querySelector(".count-badge");
  if (el) el.textContent = n;
}

function render(articles, mode) {
  const list = document.getElementById("list");
  if (!list) return;
  const visible = sortArticles(articles, mode)
    .filter((a) => !isExcluded(a) && matchesQuery(a));
  setCountBadge(visible.length);
  const parts = [];
  for (let i = 0; i < visible.length; i++) {
    parts.push(articleHTML(visible[i]));
    if ((i + 1) % AD_EVERY === 0 && i + 1 < visible.length) parts.push(AD_SLOT_HTML);
  }
  list.innerHTML = parts.join("");
  highlightFromHash(); // re-apply highlight if the list was rebuilt
}

function sortMode() {
  const el = document.querySelector('input[name="sort"]:checked');
  return el ? el.value : "date";
}

let current = [];

// True if an article passes the current country + language filters (ignores the
// per-source filter). Used to scope the "Medias" list to the active selection.
function passesCountryLang(a) {
  const country = (a.country || "").toLowerCase();
  const lang = (a.lang || "").toLowerCase();
  return (includedCountries.size === 0 || includedCountries.has(country)) &&
         (includedLangs.size === 0 || includedLangs.has(lang));
}

// "Medias" filter: clickable source toggles, persisted via ?exclude=. Only lists
// sources whose articles pass the active country/language filter, so toggling a
// country or language shows/hides its sources here too.
function buildFilters(articles) {
  const box = document.getElementById("filters");
  if (!box) return;
  box.innerHTML = "";
  const sources = [...new Set(articles.filter(passesCountryLang).map((a) => a.source))].sort();
  for (const s of sources) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = s;
    const on = () => !excluded.has(s.toLowerCase());
    btn.setAttribute("aria-pressed", String(on()));
    btn.addEventListener("click", () => {
      if (on()) excluded.add(s.toLowerCase());
      else excluded.delete(s.toLowerCase());
      btn.setAttribute("aria-pressed", String(on()));
      syncUrl();
      render(current, sortMode());
    });
    box.appendChild(btn);
  }
}

// "Countries" filter (INCLUDE model): a pressed button = country is shown. An
// empty includedCountries set means "all shown" (all pressed). Toggling off the
// first country switches to "all except", and re-selecting every country
// normalizes back to the empty = all state. Persisted via ?country=.
function buildCountryFilters(articles) {
  const box = document.getElementById("countryFilters");
  if (!box) return;
  box.innerHTML = "";
  const codes = [...new Set(articles.map((a) => (a.country || "").toUpperCase()).filter(Boolean))]
    .sort((a, b) => (COUNTRY_NAMES[a] || a).localeCompare(COUNTRY_NAMES[b] || b));
  const allLc = codes.map((c) => c.toLowerCase());
  for (const code of codes) {
    const lc = code.toLowerCase();
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = COUNTRY_NAMES[code] || code;
    const on = () => includedCountries.size === 0 || includedCountries.has(lc);
    btn.setAttribute("aria-pressed", String(on()));
    btn.addEventListener("click", () => {
      if (includedCountries.size === 0) {
        // currently all → turn this one off (include all others)
        allLc.forEach((c) => includedCountries.add(c));
        includedCountries.delete(lc);
      } else if (includedCountries.has(lc)) {
        includedCountries.delete(lc);
      } else {
        includedCountries.add(lc);
      }
      if (includedCountries.size === allLc.length) includedCountries.clear(); // all → empty (= all)
      syncUrl();
      persistCountry();             // remember the choice for next visit
      buildCountryFilters(current); // refresh pressed states across the group
      buildFilters(current);        // refresh the Medias list to match the country selection
      render(current, sortMode());
    });
    box.appendChild(btn);
  }
}

// "Languages" filter (INCLUDE model, mirrors Countries): pressed = language is
// shown; empty includedLangs = all shown. Persisted via ?lang=.
function buildLangFilters(articles) {
  const box = document.getElementById("langFilters");
  if (!box) return;
  box.innerHTML = "";
  const codes = [...new Set(articles.map((a) => (a.lang || "").toLowerCase()).filter(Boolean))]
    .sort((a, b) => (LANG_NAMES[a] || a).localeCompare(LANG_NAMES[b] || b));
  for (const code of codes) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = LANG_NAMES[code] || code;
    const on = () => includedLangs.size === 0 || includedLangs.has(code);
    btn.setAttribute("aria-pressed", String(on()));
    btn.addEventListener("click", () => {
      if (includedLangs.size === 0) {
        codes.forEach((c) => includedLangs.add(c)); // all → turn this one off
        includedLangs.delete(code);
      } else if (includedLangs.has(code)) {
        includedLangs.delete(code);
      } else {
        includedLangs.add(code);
      }
      if (includedLangs.size === codes.length) includedLangs.clear(); // all → empty (= all)
      syncUrl();
      persistLang();
      buildLangFilters(current); // refresh pressed states across the group
      buildFilters(current);     // refresh the Medias list to match the language selection
      render(current, sortMode());
    });
    box.appendChild(btn);
  }
}

// Instant filter pass over the server-rendered rows, using the data already in
// the markup (data-lang / data-country / source + title text). Runs at boot so a
// URL with filters hides non-matching rows immediately, without waiting for the
// crawled.json fetch + full re-render.
function applySsrFilter() {
  const list = document.getElementById("list");
  if (!list) return;
  let visible = 0;
  for (const li of list.querySelectorAll(".article")) {
    const country = (li.dataset.country || "").toLowerCase();
    const lang = (li.dataset.lang || "").toLowerCase();
    const srcEl = li.querySelector(".source");
    const source = (srcEl ? srcEl.textContent : "").toLowerCase();
    const titleEl = li.querySelector(".title");
    const title = (titleEl ? titleEl.textContent : "").toLowerCase();
    const hide =
      excluded.has(source) ||
      (includedCountries.size > 0 && !includedCountries.has(country)) ||
      (includedLangs.size > 0 && !includedLangs.has(lang)) ||
      (query && !(title.includes(query) || source.includes(query)));
    li.style.display = hide ? "none" : "";
    if (!hide) visible++;
  }
  setCountBadge(visible);
}

function load(url) {
  fetch(url)
    .then((r) => r.json())
    .then((data) => {
      current = data.articles;
      if (autoDefault) relaxIfEmpty(); // never leave an auto-applied default empty
      buildFilters(current);
      buildCountryFilters(current);
      buildLangFilters(current);
      // Re-render if a filter/search is active; otherwise keep the SSR markup.
      if (excluded.size || includedCountries.size || includedLangs.size || query)
        render(current, sortMode());
      // First visit: now that sources are loaded, detect and offer the welcome.
      if (firstVisit) {
        firstVisit = false;
        detectCountry().then((c) => showWelcome(c, detectLanguage()));
      }
    })
    .catch(() => {});
}

// Languages we carry for a country, most-frequent first (derived from loaded data).
function langsForCountry(code) {
  if (!code || !current.length) return [];
  const counts = {};
  for (const a of current) {
    if ((a.country || "").toLowerCase() === code.toLowerCase()) {
      const l = (a.lang || "").toLowerCase();
      if (l) counts[l] = (counts[l] || 0) + 1;
    }
  }
  return Object.keys(counts).sort((x, y) => counts[y] - counts[x]);
}

// ---------- View switching (feed / settings / more) ----------
const feedView = document.getElementById("feedView");
const settingsView = document.getElementById("settingsView");
const moreView = document.getElementById("moreView");
const feedToggle = document.getElementById("feedToggle");
const moreToggle = document.getElementById("moreToggle");

function showView(name) {
  if (feedView) feedView.hidden = name !== "feed";
  if (settingsView) settingsView.hidden = name !== "settings";
  if (moreView) moreView.hidden = name !== "more";
  if (feedToggle) feedToggle.setAttribute("aria-expanded", String(name === "settings"));
  if (moreToggle) moreToggle.setAttribute("aria-expanded", String(name === "more"));
  window.scrollTo(0, 0);
}

if (feedToggle) {
  feedToggle.addEventListener("click", () => {
    showView(settingsView && settingsView.hidden ? "settings" : "feed");
  });
}
if (moreToggle) {
  moreToggle.addEventListener("click", () => {
    showView(moreView && moreView.hidden ? "more" : "feed");
  });
}

// "Change location" — re-run detection and show the welcome popup again.
const changeLocationBtn = document.getElementById("changeLocation");
if (changeLocationBtn) {
  changeLocationBtn.addEventListener("click", () => {
    detectCountry().then((c) => showWelcome(c, detectLanguage()));
  });
}

// ---------- Mobile accordions for feed-settings groups ----------
const mobile = window.matchMedia("(max-width: 760px)");
for (const head of document.querySelectorAll(".fs-head")) {
  // <details> already toggles; on mobile we collapse via the .open class on the group
  // and suppress the native marker, so intercept and drive the class instead.
  head.addEventListener("click", (e) => {
    if (!mobile.matches) return;
    e.preventDefault();
    head.closest(".fs-group").classList.toggle("open");
  });
}

// ---------- Welcome modal & primary country/language detection ----------
const STORE_COUNTRY = "allnews.country";   // remembered primary country (csv), "" = all
const STORE_LANG = "allnews.lang";         // remembered primary language (csv), "" = all
const STORE_WELCOMED = "allnews.welcomed"; // "1" once the welcome modal was dismissed

// True when the active country/language filter came from auto-detection or a
// remembered preference (not from an explicit URL or user click). Such defaults
// get relaxed rather than ever showing an empty feed.
let autoDefault = false;
// Set at boot for a first-time home-page visit; the welcome modal is shown once
// crawled.json has loaded (so detected language can be validated against sources).
let firstVisit = false;

function lsGet(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
function lsSet(k, v) { try { localStorage.setItem(k, v); } catch (e) { /* ignore */ } }

function persistCountry() {
  lsSet(STORE_COUNTRY, [...includedCountries].join(","));
  lsSet(STORE_WELCOMED, "1");
}

function persistLang() {
  lsSet(STORE_LANG, [...includedLangs].join(","));
  lsSet(STORE_WELCOMED, "1");
}

// A browser language often has no sources in the detected country (e.g. an
// English browser in Germany). Rather than show nothing, drop the language
// constraint first, then the country, until the auto-applied default is non-empty.
function relaxIfEmpty() {
  if (!current.length) return;
  const visible = () => current.filter((a) => !isExcluded(a) && matchesQuery(a)).length;
  if (visible() > 0) return;
  if (includedLangs.size) { includedLangs.clear(); persistLang(); }
  if (visible() > 0) return;
  if (includedCountries.size) { includedCountries.clear(); persistCountry(); }
}

// Timezone → ISO country, a no-network fallback when /cdn-cgi/trace is blocked.
// Covers the countries we carry; extend alongside COUNTRY_NAMES.
const TZ_COUNTRY = {
  "Europe/Zurich": "CH", "Europe/Berlin": "DE", "Europe/Paris": "FR", "Europe/Rome": "IT",
  "Europe/Madrid": "ES", "Europe/London": "GB", "Europe/Amsterdam": "NL", "Europe/Brussels": "BE",
  "Europe/Vienna": "AT", "Europe/Lisbon": "PT", "Europe/Dublin": "IE", "Europe/Warsaw": "PL",
  "Europe/Stockholm": "SE", "Europe/Oslo": "NO", "Europe/Copenhagen": "DK", "Europe/Helsinki": "FI",
  "Europe/Athens": "GR", "Europe/Prague": "CZ", "Europe/Budapest": "HU", "Europe/Bucharest": "RO",
  "Europe/Kyiv": "UA", "Europe/Kiev": "UA", "Europe/Istanbul": "TR",
  "America/Toronto": "CA", "America/Vancouver": "CA", "America/Montreal": "CA",
  "America/Mexico_City": "MX", "America/Sao_Paulo": "BR", "America/Argentina/Buenos_Aires": "AR",
  "America/Bogota": "CO", "America/Lima": "PE",
  "America/New_York": "US", "America/Chicago": "US", "America/Denver": "US", "America/Los_Angeles": "US",
  "Australia/Sydney": "AU", "Australia/Melbourne": "AU", "Pacific/Auckland": "NZ",
  "Asia/Kolkata": "IN", "Asia/Tokyo": "JP", "Asia/Seoul": "KR", "Asia/Singapore": "SG",
  "Asia/Jakarta": "ID", "Asia/Manila": "PH", "Asia/Ho_Chi_Minh": "VN", "Asia/Karachi": "PK",
  "Asia/Jerusalem": "IL", "Asia/Qatar": "QA", "Asia/Hong_Kong": "HK",
};

// Best-effort visitor country (ISO alpha-2): Cloudflare edge IP first, then
// timezone, then the browser locale's region. null if undeterminable.
async function detectCountry() {
  try {
    const txt = await fetch("/cdn-cgi/trace", { cache: "no-store" }).then((r) => r.text());
    const m = txt.match(/^loc=([A-Z]{2})/m);
    if (m) return m[1];
  } catch (e) { /* fall through */ }
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (TZ_COUNTRY[tz]) return TZ_COUNTRY[tz];
  } catch (e) { /* fall through */ }
  const region = ((navigator.languages || [navigator.language || ""])[0] || "").split("-")[1];
  return region && /^[A-Za-z]{2}$/.test(region) ? region.toUpperCase() : null;
}

// Best-effort preferred language (ISO 639-1) from the browser, limited to the
// languages we actually carry. null if none match.
function detectLanguage() {
  for (const tag of navigator.languages || [navigator.language || ""]) {
    const code = (tag || "").split("-")[0].toLowerCase();
    if (code in LANG_NAMES) return code;
  }
  return null;
}

// Apply a single primary country / language via the include model ("" = all).
function setPrimaryCountry(code) {
  includedCountries.clear();
  if (code) includedCountries.add(code.toLowerCase());
}
function setPrimaryLang(code) {
  includedLangs.clear();
  if (code) includedLangs.add(code.toLowerCase());
}

function refreshFeed() {
  if (autoDefault) relaxIfEmpty();
  buildFilters(current); buildCountryFilters(current); buildLangFilters(current);
  if (current.length) render(current, sortMode());
  else applySsrFilter();
}

function showWelcome(code, langCode) {
  const country = code && (code in COUNTRY_NAMES) ? code : null;
  const cName = country ? COUNTRY_NAMES[country] : "around the world";
  // The detected browser language may not exist for this country (e.g. an
  // English browser visiting from Switzerland). Only offer a language the
  // country actually publishes in, falling back to its predominant one.
  let lang = langCode && (langCode in LANG_NAMES) ? langCode : null;
  if (country) {
    const avail = langsForCountry(country);
    if (avail.length && (!lang || !avail.includes(lang))) lang = avail[0];
  }
  const lName = lang ? LANG_NAMES[lang] : null;
  const sentence = lName
    ? `Based on your location you see all.news from <span class="country">${esc(cName)}</span> in <span class="lang">${esc(lName)}</span>.`
    : `Based on your location you see all.news from <span class="country">${esc(cName)}</span>.`;
  const overlay = document.createElement("div");
  overlay.id = "welcomeOverlay";
  overlay.className = "welcome-overlay";
  overlay.innerHTML =
    '<div class="welcome-modal" role="dialog" aria-modal="true" aria-labelledby="welcomeTitle">' +
    '<h2 id="welcomeTitle">Welcome.</h2>' +
    `<p>${sentence}</p>` +
    '<div class="welcome-actions">' +
    '<button type="button" class="change">Change</button>' +
    '<button type="button" class="continue">Continue ✓</button>' +
    '</div></div>';
  document.body.appendChild(overlay);
  const close = () => { overlay.remove(); lsSet(STORE_WELCOMED, "1"); };
  const apply = () => {
    setPrimaryCountry(country);
    setPrimaryLang(lang);
    autoDefault = true; // relax the combo rather than show an empty feed
    persistCountry();
    persistLang();
    close();
    refreshFeed();
  };
  // "Change" applies the detected setting, then opens the menu so the user sees
  // everything deselected except their auto-selected country/language.
  const change = () => { apply(); showView("settings"); };
  overlay.querySelector(".continue").addEventListener("click", apply);
  overlay.querySelector(".change").addEventListener("click", change);
  // The underlined country/language names are also shortcuts to change them.
  overlay.querySelectorAll(".country, .lang").forEach((el) => el.addEventListener("click", change));
}

// ---------- Boot ----------
const dayParam = new URLSearchParams(location.search).get("day");
if (dayParam) {
  // Redirect legacy ?day= URLs to static archive pages
  location.replace(`/archive/${dayParam}.html`);
} else {
  // archive/2026-06-07.html → 2026-06-07.json (sibling); else /crawled.json
  const archiveMatch = location.pathname.match(/\/archive\/(\d{4}-\d{2}-\d{2})\.html$/);
  const jsonUrl = archiveMatch ? `${archiveMatch[1]}.json` : "/crawled.json";
  const hasUrlFilter = excluded.size || includedCountries.size || includedLangs.size || query;
  if (hasUrlFilter) {
    // A filtered/shared URL wins — pre-filter the SSR rows so there's no flash.
    applySsrFilter();
  } else if (lsGet(STORE_WELCOMED)) {
    // Returning visitor: re-apply their remembered primary country + language (clean URL).
    const savedC = (lsGet(STORE_COUNTRY) || "").trim();
    const savedL = (lsGet(STORE_LANG) || "").trim();
    if (savedC) savedC.split(",").forEach((c) => includedCountries.add(c));
    if (savedL) savedL.split(",").forEach((l) => includedLangs.add(l));
    if (savedC || savedL) { autoDefault = true; applySsrFilter(); }
  } else if (!archiveMatch) {
    // First visit to the home page: show the welcome modal after load() has the data.
    firstVisit = true;
  }
  load(jsonUrl);
}

const searchInput = document.getElementById("search");
if (searchInput) {
  searchInput.value = query;
  searchInput.addEventListener("input", () => {
    query = searchInput.value.trim().toLowerCase();
    syncUrl();
    render(current, sortMode());
  });
}

// ---------- Article sharing & deep-link highlighting ----------
// "Artikel teilen" copies a link to the article's anchor on this page; arriving
// with that #hash highlights the row and scrolls it to the top.
function highlightFromHash() {
  const id = decodeURIComponent(location.hash.slice(1));
  for (const el of document.querySelectorAll(".article.highlight")) {
    el.classList.remove("highlight");
  }
  if (!id) return;
  const el = document.getElementById(id);
  if (el) {
    el.classList.add("highlight");
    el.scrollIntoView({ block: "start", behavior: "auto" });
  }
}

function shareArticle(li, btn) {
  const url = `${location.origin}${location.pathname}#${li.id}`;
  const done = () => {
    const label = btn.querySelector(".label");
    if (!label) return;
    const prev = label.textContent;
    label.textContent = "Copied!";
    setTimeout(() => { label.textContent = prev; }, 1500);
  };
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(url).then(done, done);
  } else {
    const ta = document.createElement("textarea");
    ta.value = url;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand("copy"); } catch (e) { /* ignore */ }
    ta.remove();
    done();
  }
}

document.addEventListener("click", (e) => {
  const btn = e.target.closest(".row-act.share");
  if (btn) {
    const li = btn.closest(".article");
    if (li) shareArticle(li, btn);
    // Don't keep focus on the button: :focus-within would otherwise hold the
    // row's white "card" state open after the pointer leaves.
    btn.blur();
    return;
  }
  // Title link and "Open" navigate on their own; just drop focus so
  // :focus-within doesn't leave the card stuck in its white "card" state.
  const link = e.target.closest(".article a");
  if (link) {
    link.blur();
    return;
  }
  // Clicking anywhere else on the card opens the article in a new tab —
  // unless the user is selecting text.
  const sel = window.getSelection();
  if (sel && sel.toString()) return;
  const li = e.target.closest(".article");
  if (li) {
    const title = li.querySelector("a.title");
    if (title) window.open(title.href, "_blank", "noopener");
  }
});

window.addEventListener("hashchange", highlightFromHash);
highlightFromHash(); // honor an initial #hash on the server-rendered list
