// SOURCE_COLORS is loaded from /colors.js (generated by crawler.py)

const AD_EVERY = 25; // insert an ad slot after every N visible articles
// Icons reference the shared <symbol> sprite in the page (defined in template.html)
// via <use>, so rows stay tiny. Must match the crawler's OPEN_SVG/LINK_SVG/HIDE_BTN.
const OPEN_SVG = '<svg width="18" height="18"><use href="#ico-arrow"/></svg>';
const LINK_SVG = '<svg width="18" height="18"><use href="#ico-link"/></svg>';
// Eye toggle next to the time: hides this source from the feed (#4).
const HIDE_BTN = '<button class="hide-src" type="button" aria-label="Hide source" title="Hide source"><svg width="14" height="14"><use href="#ico-eye-off"/></svg></button>';

// Origin (scheme://host) of an article URL — the source portal's home (#4).
function portalHome(u) {
  try { return new URL(u).origin; } catch (e) { return u; }
}

// Stable per-article anchor id (mirrors article_id() in crawler.py). Used for
// "Share" deep-links: https://all.news/#<id>
function slugify(s) {
  return (s || "")
    .toLowerCase()
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/^-+|-+$/g, "");
}
function djb2(s) {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h * 33) + s.charCodeAt(i)) >>> 0;
  return h;
}
function articleId(a) {
  return `${slugify(a.title)}-${djb2(a.url).toString(16)}`;
}

function fmtTime(s) {
  if (!s) return "";
  const d = new Date(s);
  if (isNaN(d)) return "";
  // Swiss local HH:MM (mirrors fmt_time in crawler.py)
  return d.toLocaleString("de-CH", {
    timeZone: "Europe/Zurich",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function ts(a) {
  const d = new Date(a.published);
  return isNaN(d) ? 0 : d.getTime();
}

// Preferred source order; listed sources rank first (in this order), rest after.
// Prioritize sources with fewer updates for fairer visibility.
const SOURCE_PRIORITY = [
  "Inside Paradeplatz",
  "Infosperber",
  "Rathuus",
  "Inside IT",
  "Nebelspalter",
  "Bilanz",
  "Republik",
  "Weltwoche",
  "NZZ",
];
function prio(a) {
  const i = SOURCE_PRIORITY.indexOf(a.source);
  return i === -1 ? SOURCE_PRIORITY.length : i;
}

function sortArticles(articles, mode) {
  const out = articles.slice();
  if (mode === "source") {
    out.sort((a, b) => a.source.localeCompare(b.source) || ts(b) - ts(a));
  } else {
    out.sort((a, b) => ts(b) - ts(a) || prio(a) - prio(b));
  }
  return out;
}

// Excluded sources (lowercased), persisted in the URL: ?exclude=blick,watson
const excluded = new Set(
  (new URLSearchParams(location.search).get("exclude") || "")
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
);
// Country / language filters use an INCLUDE model with an explicit "all" flag:
//   <flag> true                      → show all (group header "select all")
//   <flag> false + non-empty set     → show only those
//   <flag> false + empty set         → show none (group header "deselect all")
// Persisted as ?country=ch,de / ?lang=de — param absent = all, empty = none.
// The welcome modal seeds the country set with the visitor's primary country.
const _params = new URLSearchParams(location.search);
const _parseSet = (name) =>
  new Set((_params.get(name) || "").split(",").map((s) => s.trim().toLowerCase()).filter(Boolean));
const includedCountries = _parseSet("country");
let countriesAll = _params.get("country") === null; // no param → all countries
const includedLangs = _parseSet("lang");
let langsAll = _params.get("lang") === null;         // no param → all languages

function countryAllowed(c) { return countriesAll || includedCountries.has((c || "").toLowerCase()); }
function langAllowed(l) { return langsAll || includedLangs.has((l || "").toLowerCase()); }
// ISO 3166-1 alpha-2 -> display name. Extend as the source scope widens.
const COUNTRY_NAMES = {
  CH: "Switzerland", DE: "Germany", FR: "France",
  GB: "United Kingdom", US: "United States", IT: "Italy", ES: "Spain",
  NL: "Netherlands", BE: "Belgium", AT: "Austria", PT: "Portugal", IE: "Ireland",
  PL: "Poland", SE: "Sweden", NO: "Norway", DK: "Denmark", FI: "Finland",
  GR: "Greece", CZ: "Czechia", HU: "Hungary", RO: "Romania", UA: "Ukraine", TR: "Turkey",
  CA: "Canada", MX: "Mexico", BR: "Brazil", AR: "Argentina", CO: "Colombia", PE: "Peru",
  AU: "Australia", NZ: "New Zealand",
  IN: "India", JP: "Japan", KR: "South Korea", SG: "Singapore", ID: "Indonesia",
  PH: "Philippines", VN: "Vietnam", PK: "Pakistan", IL: "Israel", QA: "Qatar", HK: "Hong Kong",
  CN: "China", RU: "Russia",
};
// ISO 639-1 -> display name (shown in the source's own language).
const LANG_NAMES = {
  de: "Deutsch", fr: "Français", en: "English", it: "Italiano", es: "Español",
  nl: "Nederlands", pt: "Português", pl: "Polski", sv: "Svenska", no: "Norsk",
  da: "Dansk", fi: "Suomi", el: "Ελληνικά", cs: "Čeština", hu: "Magyar", ro: "Română",
  uk: "Українська", tr: "Türkçe", ja: "日本語", id: "Bahasa Indonesia", vi: "Tiếng Việt",
  he: "עברית", ar: "العربية", zh: "中文", ru: "Русский",
};

const EN_MONTHS = ["", "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];
function fmtDayEn(iso) {
  const [y, m, d] = (iso || "").split("-");
  return EN_MONTHS[+m] ? `${+d} ${EN_MONTHS[+m]} ${y}` : iso;
}
// Today's date (YYYY-MM-DD) in Swiss local time — matches the crawler's "today".
function todayISO() {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Europe/Zurich", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(new Date());
}
// Current filter as a query string ("" when nothing is filtered), so archive
// day links can carry the active country/language/source/search selection (#2).
function filterQuery() {
  const p = new URLSearchParams();
  if (excluded.size) p.set("exclude", [...excluded].join(","));
  if (!countriesAll) p.set("country", [...includedCountries].join(","));
  if (!langsAll) p.set("lang", [...includedLangs].join(","));
  if (query) p.set("q", query);
  const s = p.toString();
  return s ? "?" + s : "";
}

// Badge color: brand color if listed, else a stable hashed hue (mirrors
// color_for() in crawler.py) so every source gets a distinct color.
function colorFor(s) {
  return SOURCE_COLORS[s] || `hsl(${djb2(s) % 360}, 65%, 45%)`;
}

// Pill text colour: black on a light background, white on a dark one (mirrors
// text_color() in crawler.py).
function textColor(bg) {
  const m = /^#([0-9a-f]{6})$/i.exec(bg || "");
  if (!m) return "#fff";
  const n = parseInt(m[1], 16);
  const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255 > 0.6 ? "#000" : "#fff";
}

function isExcluded(a) {
  return excluded.has(a.source.toLowerCase()) ||
         !countryAllowed(a.country) ||
         !langAllowed(a.lang);
}

// Free-text search over title + source, persisted in the URL: ?q=…
let query = (new URLSearchParams(location.search).get("q") || "").trim().toLowerCase();

function matchesQuery(a) {
  if (!query) return true;
  return a.title.toLowerCase().includes(query) ||
         a.source.toLowerCase().includes(query);
}

function syncUrl() {
  const params = new URLSearchParams(location.search);
  if (excluded.size) params.set("exclude", [...excluded].join(","));
  else params.delete("exclude");
  // flag true (all) → omit param; otherwise write the set (empty string = none).
  if (countriesAll) params.delete("country");
  else params.set("country", [...includedCountries].join(","));
  if (langsAll) params.delete("lang");
  else params.set("lang", [...includedLangs].join(","));
  if (query) params.set("q", query);
  else params.delete("q");
  const qs = params.toString();
  history.replaceState(null, "", location.pathname + (qs ? "?" + qs : ""));
}

// HTML-escape for text and attribute values (mirrors escape() in crawler.py).
function esc(s) {
  return (s == null ? "" : String(s))
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

// One row as an HTML string (mirrors render_article_html in crawler.py). Building
// the whole list as a single string + one innerHTML assignment is far faster than
// per-node DOM construction; clicks are handled by delegation, so no per-row
// listeners are needed.
function articleHTML(a) {
  const color = colorFor(a.source);
  const fg = textColor(color);
  const url = esc(a.url);
  const home = esc(portalHome(a.url));
  return `<li class="article" id="${esc(articleId(a))}" data-lang="${esc(a.lang || "de")}" data-country="${esc(a.country || "CH")}">` +
    `<div class="meta-col">` +
    `<a class="source" href="${home}" target="_blank" rel="noopener" style="background:${color};color:${fg}">${esc(a.source)}</a>` +
    `<span class="time">${esc(fmtTime(a.published))} ${HIDE_BTN}</span>` +
    `</div>` +
    `<a class="title" href="${url}" target="_blank" rel="noopener">${esc(a.title)}</a>` +
    `<div class="row-actions">` +
    `<a class="row-act open" href="${url}" target="_blank" rel="noopener"><span class="label">Open article</span> ${OPEN_SVG}</a>` +
    `<button class="row-act share" type="button"><span class="label">Share article</span> ${LINK_SVG}</button>` +
    `</div></li>`;
}

const AD_SLOT_HTML = '<li class="ad-slot">Werbung</li>';
const PAGE = 120; // articles rendered per lazy batch (matches SSR_LIMIT head)

// Reflect the number of currently-visible articles in the wordmark badge.
function setCountBadge(n) {
  const el = document.querySelector(".count-badge");
  if (el) el.textContent = n;
}

// Lazy/windowed rendering: render() lays down the first PAGE rows + a scroll
// sentinel; appendBatch() adds the next PAGE as the sentinel nears the viewport.
// The full list can be thousands of rows, so we never build them all at once.
let visibleArticles = [];
let shownCount = 0;
let scrollObserver = null;

function render(articles, mode) {
  const list = document.getElementById("list");
  if (!list) return;
  visibleArticles = sortArticles(articles, mode)
    .filter((a) => !isExcluded(a) && matchesQuery(a));
  setCountBadge(visibleArticles.length);
  if (scrollObserver) { scrollObserver.disconnect(); scrollObserver = null; }
  list.innerHTML = "";
  shownCount = 0;
  if (!visibleArticles.length && query) {
    // No matches for the search term — say so instead of a blank list (#25).
    list.innerHTML = `<li class="no-results">No results for “${esc(query)}”</li>`;
    return;
  }
  appendBatch();
  ensureHashVisible(); // render far enough to reveal a deep-linked article
  highlightFromHash();
}

function appendBatch() {
  const list = document.getElementById("list");
  if (!list) return;
  const end = Math.min(shownCount + PAGE, visibleArticles.length);
  const parts = [];
  for (let i = shownCount; i < end; i++) {
    parts.push(articleHTML(visibleArticles[i]));
    if ((i + 1) % AD_EVERY === 0 && i + 1 < visibleArticles.length) parts.push(AD_SLOT_HTML);
  }
  const sentinel = document.getElementById("scrollSentinel");
  if (sentinel) sentinel.insertAdjacentHTML("beforebegin", parts.join(""));
  else list.insertAdjacentHTML("beforeend", parts.join(""));
  shownCount = end;
  updateSentinel();
}

function updateSentinel() {
  const list = document.getElementById("list");
  let sentinel = document.getElementById("scrollSentinel");
  if (shownCount >= visibleArticles.length) { // all rendered — tear down
    if (sentinel) sentinel.remove();
    if (scrollObserver) { scrollObserver.disconnect(); scrollObserver = null; }
    return;
  }
  if (!sentinel) {
    sentinel = document.createElement("li");
    sentinel.id = "scrollSentinel";
    sentinel.className = "scroll-sentinel";
    list.appendChild(sentinel);
    scrollObserver = new IntersectionObserver((entries) => {
      if (entries.some((e) => e.isIntersecting)) appendBatch();
    }, { rootMargin: "1000px" });
    scrollObserver.observe(sentinel);
  } else {
    list.appendChild(sentinel); // keep it last after the freshly inserted rows
  }
}

// If the URL targets an article (#id) beyond the current window, render up to it.
function ensureHashVisible() {
  const id = decodeURIComponent(location.hash.slice(1));
  if (!id || shownCount >= visibleArticles.length) return;
  const idx = visibleArticles.findIndex((a) => articleId(a) === id);
  while (idx >= shownCount && shownCount < visibleArticles.length) appendBatch();
}

function sortMode() {
  const el = document.querySelector('input[name="sort"]:checked');
  return el ? el.value : "date";
}

let current = [];

// True if an article passes the current country + language filters (ignores the
// per-source filter). Used to scope the "Medias" list to the active selection.
function passesCountryLang(a) {
  return countryAllowed(a.country) && langAllowed(a.lang);
}

// "Medias" filter: clickable source toggles, persisted via ?exclude=. Only lists
// sources whose articles pass the active country/language filter, so toggling a
// country or language shows/hides its sources here too.
function buildFilters(articles) {
  const box = document.getElementById("filters");
  if (!box) return;
  box.innerHTML = "";
  const sources = [...new Set(articles.filter(passesCountryLang).map((a) => a.source))].sort();
  for (const s of sources) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = s;
    const on = () => !excluded.has(s.toLowerCase());
    btn.setAttribute("aria-pressed", String(on()));
    btn.addEventListener("click", () => {
      if (on()) excluded.add(s.toLowerCase());
      else excluded.delete(s.toLowerCase());
      btn.setAttribute("aria-pressed", String(on()));
      syncUrl();
      render(current, sortMode());
    });
    box.appendChild(btn);
  }
}

// "Countries" filter (INCLUDE model + countriesAll flag): pressed = country shown.
// The group header does select-all / deselect-all (see wireHeaderToggle).
function buildCountryFilters(articles) {
  const box = document.getElementById("countryFilters");
  if (!box) return;
  box.innerHTML = "";
  const codes = [...new Set(articles.map((a) => (a.country || "").toUpperCase()).filter(Boolean))]
    .sort((a, b) => (COUNTRY_NAMES[a] || a).localeCompare(COUNTRY_NAMES[b] || b));
  const allLc = codes.map((c) => c.toLowerCase());
  for (const code of codes) {
    const lc = code.toLowerCase();
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = COUNTRY_NAMES[code] || code;
    btn.setAttribute("aria-pressed", String(countryAllowed(lc)));
    btn.addEventListener("click", () => {
      if (countriesAll) {                 // materialize "all", then turn this one off
        allLc.forEach((c) => includedCountries.add(c));
        countriesAll = false;
        includedCountries.delete(lc);
      } else if (includedCountries.has(lc)) {
        includedCountries.delete(lc);
      } else {
        includedCountries.add(lc);
      }
      if (includedCountries.size === allLc.length) { // everything selected → "all"
        countriesAll = true;
        includedCountries.clear();
      }
      pruneLangsToCountries();      // drop languages the selection no longer publishes
      afterFilterChange();
    });
    box.appendChild(btn);
  }
}

// Drop selected languages not published by the currently-selected countries, so
// switching countries never leaves a stale language pick that empties the feed.
function pruneLangsToCountries() {
  if (langsAll || countriesAll) return;
  const avail = new Set(current
    .filter((a) => includedCountries.has((a.country || "").toLowerCase()))
    .map((a) => (a.lang || "").toLowerCase()));
  for (const l of [...includedLangs]) if (!avail.has(l)) includedLangs.delete(l);
}

// Persist + rebuild all panels + re-render after any country/language change.
function afterFilterChange() {
  syncUrl();
  persistCountry();
  persistLang();
  buildCountryFilters(current);
  buildLangFilters(current);
  buildFilters(current);
  updateAllToggles();
  updateArchiveDayLinks();
  render(current, sortMode());
}

// "Select all" / "Deselect all" button label reflects each group's state (#2).
function updateAllToggles() {
  const set = (group, allOn) => {
    const btn = document.querySelector(`.fs-all[data-group="${group}"]`);
    if (btn) btn.textContent = allOn ? "Deselect all" : "Select all";
  };
  set("country", countriesAll);
  set("lang", langsAll);
  set("media", excluded.size === 0); // no source excluded = all shown
}

// Archive section: today's date (the home feed, active) + up to 30 past archive
// days, all listed uniformly. Built once from /archive/index.json; each past-day
// link carries the active filter.
let archiveDatesPromise = null;
function loadArchiveDates() {
  if (archiveDatesPromise) return archiveDatesPromise;
  archiveDatesPromise = fetch("/archive/index.json")
    .then((r) => r.json())
    .then((idx) => { buildArchiveDays(idx.dates || []); return idx.dates; })
    .catch(() => { archiveDatesPromise = null; });
  return archiveDatesPromise;
}
function buildArchiveDays(dates) {
  const box = document.getElementById("archiveDays");
  if (!box) return;
  box.innerHTML = "";
  const today = todayISO();
  const a0 = document.createElement("a");
  a0.className = "today";
  a0.dataset.base = "/";
  a0.textContent = fmtDayEn(today); // today's date (the home feed), not the word "Today"
  box.appendChild(a0);
  const past = dates.slice().sort().reverse().filter((d) => d < today).slice(0, 30);
  for (const d of past) {
    const a = document.createElement("a");
    a.className = "past";
    a.dataset.base = `/archive/${d}.html`;
    a.target = "_blank";          // open the archive day in a new tab
    a.rel = "noopener";
    a.textContent = fmtDayEn(d);
    box.appendChild(a);
  }
  updateArchiveDayLinks();
}
function updateArchiveDayLinks() {
  const q = filterQuery();
  for (const a of document.querySelectorAll("#archiveDays a[data-base]")) {
    a.href = (a.dataset.base || "/") + q;
  }
}

// Group-header select-all / deselect-all toggles (desktop).
function toggleAllCountries() {
  countriesAll = !countriesAll;           // all ⇄ none
  includedCountries.clear();
  pruneLangsToCountries();
  afterFilterChange();
}
function toggleAllLangs() {
  langsAll = !langsAll;                    // all ⇄ none
  includedLangs.clear();
  afterFilterChange();
}
function toggleAllMedia() {
  if (excluded.size === 0) {               // all shown → exclude every source
    for (const a of current) excluded.add((a.source || "").toLowerCase());
  } else {                                 // some/none shown → clear (show all)
    excluded.clear();
  }
  afterFilterChange();
}

// "Languages" filter (INCLUDE model + langsAll flag, mirrors Countries): pressed =
// shown. Only lists languages the selected countries publish. The group header
// does select-all / deselect-all (see wireHeaderToggle).
function buildLangFilters(articles) {
  const box = document.getElementById("langFilters");
  if (!box) return;
  box.innerHTML = "";
  const pool = articles.filter((a) => countryAllowed(a.country));
  const codes = [...new Set(pool.map((a) => (a.lang || "").toLowerCase()).filter(Boolean))]
    .sort((a, b) => (LANG_NAMES[a] || a).localeCompare(LANG_NAMES[b] || b));
  for (const code of codes) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "opt";
    btn.textContent = LANG_NAMES[code] || code;
    btn.setAttribute("aria-pressed", String(langAllowed(code)));
    btn.addEventListener("click", () => {
      if (langsAll) {                 // materialize "all available", then turn this off
        codes.forEach((c) => includedLangs.add(c));
        langsAll = false;
        includedLangs.delete(code);
      } else if (includedLangs.has(code)) {
        includedLangs.delete(code);
      } else {
        includedLangs.add(code);
      }
      if (includedLangs.size === codes.length) { langsAll = true; includedLangs.clear(); }
      afterFilterChange();
    });
    box.appendChild(btn);
  }
}

// Instant filter pass over the server-rendered rows, using the data already in
// the markup (data-lang / data-country / source + title text). Runs at boot so a
// URL with filters hides non-matching rows immediately, without waiting for the
// crawled.json fetch + full re-render.
function applySsrFilter() {
  const list = document.getElementById("list");
  if (!list) return;
  let visible = 0;
  for (const li of list.querySelectorAll(".article")) {
    const country = (li.dataset.country || "").toLowerCase();
    const lang = (li.dataset.lang || "").toLowerCase();
    const srcEl = li.querySelector(".source");
    const source = (srcEl ? srcEl.textContent : "").toLowerCase();
    const titleEl = li.querySelector(".title");
    const title = (titleEl ? titleEl.textContent : "").toLowerCase();
    const hide =
      excluded.has(source) ||
      !countryAllowed(country) ||
      !langAllowed(lang) ||
      (query && !(title.includes(query) || source.includes(query)));
    li.style.display = hide ? "none" : "";
    if (!hide) visible++;
  }
  setCountBadge(visible);
}

// Fetch the dataset (crawled.json on the home page, the day's archive JSON on an
// archive page) once and build the filter panels. Memoized so it can be called
// lazily — archive pages only load it when the user filters/searches, keeping a
// plain archive view to just its static HTML (scales as days get bigger).
let DATA_URL = "/crawled.json";
let dataPromise = null;
function loadData() {
  if (dataPromise) return dataPromise;
  dataPromise = fetch(DATA_URL)
    .then((r) => r.json())
    .then((data) => {
      current = data.articles;
      if (autoDefault) relaxIfEmpty(); // never leave an auto-applied default empty
      buildFilters(current);
      buildCountryFilters(current);
      buildLangFilters(current);
      updateAllToggles();
      return current;
    })
    .catch(() => { dataPromise = null; }); // allow retry
  return dataPromise;
}

// Languages we carry for a country, most-frequent first (derived from loaded data).
function langsForCountry(code) {
  if (!code || !current.length) return [];
  const counts = {};
  for (const a of current) {
    if ((a.country || "").toLowerCase() === code.toLowerCase()) {
      const l = (a.lang || "").toLowerCase();
      if (l) counts[l] = (counts[l] || 0) + 1;
    }
  }
  return Object.keys(counts).sort((x, y) => counts[y] - counts[x]);
}

// ---------- View switching (feed / settings / more) ----------
const feedView = document.getElementById("feedView");
const settingsView = document.getElementById("settingsView");
const moreView = document.getElementById("moreView");
const filterToggle = document.getElementById("filterToggle");
const moreToggle = document.getElementById("moreToggle");

function showView(name) {
  if (feedView) feedView.hidden = name !== "feed";
  if (settingsView) settingsView.hidden = name !== "settings";
  if (moreView) moreView.hidden = name !== "more";
  if (filterToggle) filterToggle.setAttribute("aria-expanded", String(name === "settings"));
  if (moreToggle) moreToggle.setAttribute("aria-expanded", String(name === "more"));
  window.scrollTo(0, 0);
}

// "Filter" nav opens the filter panel (the logo is now a plain home link). The
// panel filters the home feed and — on archive day pages — that day's articles.
function toggleSettings() {
  const opening = settingsView && settingsView.hidden;
  showView(opening ? "settings" : "feed");
  if (opening) {
    loadData();          // ensure filter panels are populated (esp. on archive pages)
    loadArchiveDates();  // populate the Archive day list (Today + last 10 days)
  }
}
if (filterToggle) filterToggle.addEventListener("click", toggleSettings);
if (moreToggle) {
  moreToggle.addEventListener("click", () => {
    showView(moreView && moreView.hidden ? "more" : "feed");
  });
}

// ---------- Feed-settings group headers ----------
// On mobile the header expands/collapses the group (the list is hidden until
// open). On desktop the list is always visible, so the header is just a label —
// select-all / deselect-all is the explicit ".fs-all" button (#2).
const mobile = window.matchMedia("(max-width: 760px)");
for (const head of document.querySelectorAll(".fs-head")) {
  head.addEventListener("click", (e) => {
    if (mobile.matches) {
      e.preventDefault();
      head.closest(".fs-group").classList.toggle("open");
    }
  });
}

// "Select all" / "Deselect all" buttons under each group.
for (const btn of document.querySelectorAll(".fs-all")) {
  btn.addEventListener("click", () => {
    const g = btn.dataset.group;
    if (g === "country") toggleAllCountries();
    else if (g === "lang") toggleAllLangs();
    else if (g === "media") toggleAllMedia();
  });
}

// ---------- Welcome modal & primary country/language detection ----------
const STORE_COUNTRY = "allnews.country";   // remembered primary country (csv), "" = all
const STORE_LANG = "allnews.lang";         // remembered primary language (csv), "" = all
const STORE_WELCOMED = "allnews.welcomed"; // "1" once the welcome modal was dismissed

// True when the active country/language filter came from auto-detection or a
// remembered preference (not from an explicit URL or user click). Such defaults
// get relaxed rather than ever showing an empty feed.
let autoDefault = false;
// Set at boot for a first-time home-page visit; the welcome modal is shown once
// crawled.json has loaded (so detected language can be validated against sources).
let firstVisit = false;

function lsGet(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
function lsSet(k, v) { try { localStorage.setItem(k, v); } catch (e) { /* ignore */ } }

function persistCountry() {
  lsSet(STORE_COUNTRY, countriesAll ? "all" : [...includedCountries].join(","));
  lsSet(STORE_WELCOMED, "1");
}

function persistLang() {
  lsSet(STORE_LANG, langsAll ? "all" : [...includedLangs].join(","));
  lsSet(STORE_WELCOMED, "1");
}

// Re-apply the visitor's remembered primary country + language (clean URL).
// Stored value: "all" | "" (none) | csv of codes. Used on a returning home-page
// visit and on archive day pages, so the feed and the archive share defaults.
// Returns true if any default was applied. Pre-filters the SSR rows immediately.
function applySavedDefaults() {
  const savedC = lsGet(STORE_COUNTRY);
  const savedL = lsGet(STORE_LANG);
  if (savedC !== null) {
    includedCountries.clear();
    countriesAll = savedC === "all";
    if (!countriesAll) savedC.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean).forEach((c) => includedCountries.add(c));
  }
  if (savedL !== null) {
    includedLangs.clear();
    langsAll = savedL === "all";
    if (!langsAll) savedL.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean).forEach((l) => includedLangs.add(l));
  }
  if (savedC !== null || savedL !== null) { autoDefault = true; applySsrFilter(); return true; }
  return false;
}

// A browser language often has no sources in the detected country (e.g. an
// English browser in Germany). Rather than show nothing, drop the language
// constraint first, then the country, until the auto-applied default is non-empty.
function relaxIfEmpty() {
  if (!current.length) return;
  const visible = () => current.filter((a) => !isExcluded(a) && matchesQuery(a)).length;
  if (visible() > 0) return;
  if (!langsAll) { langsAll = true; includedLangs.clear(); persistLang(); }
  if (visible() > 0) return;
  if (!countriesAll) { countriesAll = true; includedCountries.clear(); persistCountry(); }
}

// Timezone → ISO country, a no-network fallback when /cdn-cgi/trace is blocked.
// Covers the countries we carry; extend alongside COUNTRY_NAMES.
const TZ_COUNTRY = {
  "Europe/Zurich": "CH", "Europe/Berlin": "DE", "Europe/Paris": "FR", "Europe/Rome": "IT",
  "Europe/Madrid": "ES", "Europe/London": "GB", "Europe/Amsterdam": "NL", "Europe/Brussels": "BE",
  "Europe/Vienna": "AT", "Europe/Lisbon": "PT", "Europe/Dublin": "IE", "Europe/Warsaw": "PL",
  "Europe/Stockholm": "SE", "Europe/Oslo": "NO", "Europe/Copenhagen": "DK", "Europe/Helsinki": "FI",
  "Europe/Athens": "GR", "Europe/Prague": "CZ", "Europe/Budapest": "HU", "Europe/Bucharest": "RO",
  "Europe/Kyiv": "UA", "Europe/Kiev": "UA", "Europe/Istanbul": "TR",
  "America/Toronto": "CA", "America/Vancouver": "CA", "America/Montreal": "CA",
  "America/Mexico_City": "MX", "America/Sao_Paulo": "BR", "America/Argentina/Buenos_Aires": "AR",
  "America/Bogota": "CO", "America/Lima": "PE",
  "America/New_York": "US", "America/Chicago": "US", "America/Denver": "US", "America/Los_Angeles": "US",
  "Australia/Sydney": "AU", "Australia/Melbourne": "AU", "Pacific/Auckland": "NZ",
  "Asia/Kolkata": "IN", "Asia/Tokyo": "JP", "Asia/Seoul": "KR", "Asia/Singapore": "SG",
  "Asia/Jakarta": "ID", "Asia/Manila": "PH", "Asia/Ho_Chi_Minh": "VN", "Asia/Karachi": "PK",
  "Asia/Jerusalem": "IL", "Asia/Qatar": "QA", "Asia/Hong_Kong": "HK",
  "Asia/Shanghai": "CN", "Asia/Chongqing": "CN", "Asia/Urumqi": "CN",
  "Europe/Moscow": "RU", "Europe/Samara": "RU", "Asia/Yekaterinburg": "RU",
  "Asia/Novosibirsk": "RU", "Asia/Krasnoyarsk": "RU", "Asia/Vladivostok": "RU",
};

// Best-effort visitor country (ISO alpha-2): Cloudflare edge IP first, then
// timezone, then the browser locale's region. null if undeterminable.
async function detectCountry() {
  try {
    const txt = await fetch("/cdn-cgi/trace", { cache: "no-store" }).then((r) => r.text());
    const m = txt.match(/^loc=([A-Z]{2})/m);
    if (m) return m[1];
  } catch (e) { /* fall through */ }
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (TZ_COUNTRY[tz]) return TZ_COUNTRY[tz];
  } catch (e) { /* fall through */ }
  const region = ((navigator.languages || [navigator.language || ""])[0] || "").split("-")[1];
  return region && /^[A-Za-z]{2}$/.test(region) ? region.toUpperCase() : null;
}

// Best-effort preferred language (ISO 639-1) from the browser, limited to the
// languages we actually carry. null if none match.
function detectLanguage() {
  for (const tag of navigator.languages || [navigator.language || ""]) {
    const code = (tag || "").split("-")[0].toLowerCase();
    if (code in LANG_NAMES) return code;
  }
  return null;
}

// Apply a single primary country / language via the include model ("" = all).
function setPrimaryCountry(code) {
  includedCountries.clear();
  countriesAll = !code;
  if (code) includedCountries.add(code.toLowerCase());
}
function setPrimaryLang(code) {
  includedLangs.clear();
  langsAll = !code;
  if (code) includedLangs.add(code.toLowerCase());
}

function refreshFeed() {
  if (autoDefault) relaxIfEmpty();
  buildFilters(current); buildCountryFilters(current); buildLangFilters(current);
  updateAllToggles(); updateArchiveDayLinks();
  if (current.length) render(current, sortMode());
  else applySsrFilter();
}

function showWelcome(code, langCode) {
  const country = code && (code in COUNTRY_NAMES) ? code : null;
  const cName = country ? COUNTRY_NAMES[country] : "around the world";
  // The detected browser language may not exist for this country (e.g. an
  // English browser visiting from Switzerland). Only offer a language the
  // country actually publishes in, falling back to its predominant one.
  let lang = langCode && (langCode in LANG_NAMES) ? langCode : null;
  if (country) {
    const avail = langsForCountry(country);
    if (avail.length && (!lang || !avail.includes(lang))) lang = avail[0];
  }
  const lName = lang ? LANG_NAMES[lang] : null;
  const sentence = lName
    ? `Based on your location you see all.news from <span class="country">${esc(cName)}</span> in <span class="lang">${esc(lName)}</span>.`
    : `Based on your location you see all.news from <span class="country">${esc(cName)}</span>.`;
  const overlay = document.createElement("div");
  overlay.id = "welcomeOverlay";
  overlay.className = "welcome-overlay";
  overlay.innerHTML =
    '<div class="welcome-modal" role="dialog" aria-modal="true" aria-labelledby="welcomeTitle">' +
    '<h2 id="welcomeTitle">Welcome.</h2>' +
    `<p>${sentence}</p>` +
    '<div class="welcome-actions">' +
    '<button type="button" class="change">Change</button>' +
    '<button type="button" class="continue">Continue ✓</button>' +
    '</div></div>';
  document.body.appendChild(overlay);
  const close = () => { overlay.remove(); lsSet(STORE_WELCOMED, "1"); };
  const apply = () => {
    setPrimaryCountry(country);
    setPrimaryLang(lang);
    autoDefault = true; // relax the combo rather than show an empty feed
    persistCountry();
    persistLang();
    close();
    refreshFeed();
  };
  // "Change" applies the detected setting, then opens the menu so the user sees
  // everything deselected except their auto-selected country/language.
  const change = () => { apply(); showView("settings"); };
  overlay.querySelector(".continue").addEventListener("click", apply);
  overlay.querySelector(".change").addEventListener("click", change);
  // The underlined country/language names are also shortcuts to change them.
  overlay.querySelectorAll(".country, .lang").forEach((el) => el.addEventListener("click", change));
}

// ---------- Boot ----------
const dayParam = new URLSearchParams(location.search).get("day");
if (dayParam) {
  // Redirect legacy ?day= URLs to static archive pages
  location.replace(`/archive/${dayParam}.html`);
} else {
  // archive/2026-06-07.html (or -2, -3 …) → 2026-06-07.json (sibling); else /crawled.json
  const archiveMatch = location.pathname.match(/\/archive\/(\d{4}-\d{2}-\d{2})(?:-\d+)?\.html$/);
  DATA_URL = archiveMatch ? `${archiveMatch[1]}.json` : "/crawled.json";
  const hasUrlFilter = excluded.size || !countriesAll || !langsAll || query;

  if (archiveMatch) {
    // Archive day page: static paginated HTML. Apply an explicit URL filter or
    // the visitor's remembered defaults, then re-render that day from its JSON.
    // (The Filter menu is present via the template on every archive day page.)
    if (hasUrlFilter) {
      applySsrFilter();
      loadData().then(() => { if (current.length) render(current, sortMode()); });
    } else if (applySavedDefaults()) {
      loadData().then(() => { if (current.length) render(current, sortMode()); });
    }
  } else {
    // Home page
    if (hasUrlFilter) {
      applySsrFilter(); // pre-filter the SSR head so there's no flash
    } else if (lsGet(STORE_WELCOMED)) {
      applySavedDefaults(); // returning visitor: re-apply remembered country/lang
    } else {
      firstVisit = true; // welcome modal after data loads
    }
    loadData().then(() => {
      if (current.length) render(current, sortMode()); // home always takes over (windowed)
      if (firstVisit) {
        firstVisit = false;
        detectCountry().then((c) => showWelcome(c, detectLanguage()));
      }
    });
  }
}

const searchInput = document.getElementById("search");
const searchClear = document.getElementById("searchClear");
// Toggle the magnifier ⇄ × icon based on whether there's a query.
function syncSearchIcon() {
  const wrap = searchInput && searchInput.closest(".search-wrap");
  if (wrap) wrap.classList.toggle("has-query", !!searchInput.value);
}
if (searchInput) {
  searchInput.value = query;
  syncSearchIcon();
  searchInput.addEventListener("input", () => {
    query = searchInput.value.trim().toLowerCase();
    syncSearchIcon();
    syncUrl();
    loadData().then(() => render(current, sortMode())); // archive pages fetch on first search
  });
}
if (searchClear) {
  searchClear.addEventListener("click", () => {
    if (!searchInput) return;
    searchInput.value = "";
    query = "";
    syncSearchIcon();
    syncUrl();
    searchInput.focus();
    loadData().then(() => render(current, sortMode()));
  });
}

// ---------- Article sharing & deep-link highlighting ----------
// "Share" copies a link to the article's anchor on this page; arriving
// with that #hash highlights the row and scrolls it to the top.
function highlightFromHash() {
  const id = decodeURIComponent(location.hash.slice(1));
  for (const el of document.querySelectorAll(".article.highlight")) {
    el.classList.remove("highlight");
  }
  if (!id) return;
  const el = document.getElementById(id);
  if (el) {
    el.classList.add("highlight");
    el.scrollIntoView({ block: "start", behavior: "auto" });
  }
}

function shareArticle(li, btn) {
  const url = `${location.origin}${location.pathname}#${li.id}`;
  const done = () => {
    const label = btn.querySelector(".label");
    if (!label || btn.dataset.copied) return; // guard against rapid re-clicks
    const prev = label.textContent;
    btn.dataset.copied = "1";
    label.textContent = "Link copied ✓";
    setTimeout(() => { label.textContent = prev; delete btn.dataset.copied; }, 1500);
  };
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(url).then(done, done);
  } else {
    const ta = document.createElement("textarea");
    ta.value = url;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand("copy"); } catch (e) { /* ignore */ }
    ta.remove();
    done();
  }
}

// Hide / unhide a source (reuses the Medias exclude model), then refresh panels.
function setSourceHidden(name, hidden) {
  const lc = name.toLowerCase();
  if (hidden) excluded.add(lc); else excluded.delete(lc);
  syncUrl();
  if (current.length) { buildFilters(current); render(current, sortMode()); }
  else applySsrFilter();
}

// Confirmation popup before hiding a source (#4): explains the action and points
// to where it can be undone, so an accidental click never silently hides a source.
function confirmHide(name) {
  const overlay = document.createElement("div");
  overlay.className = "confirm-overlay";
  overlay.innerHTML =
    '<div class="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="confirmTitle">' +
    '<h2 id="confirmTitle">Hide this provider?</h2>' +
    '<p>You can always show it again in your feed ' +
    '<button type="button" class="settings-link">settings <svg width="12" height="12"><use href="#ico-arrow"/></svg></button></p>' +
    '<div class="confirm-actions">' +
    '<button type="button" class="cancel">No, cancel ✕</button>' +
    '<button type="button" class="confirm">Yes, hide ✓</button>' +
    '</div></div>';
  document.body.appendChild(overlay);
  const close = () => { overlay.remove(); document.removeEventListener("keydown", onKey); };
  const onKey = (ev) => { if (ev.key === "Escape") close(); };
  document.addEventListener("keydown", onKey);
  overlay.addEventListener("click", (ev) => { if (ev.target === overlay) close(); });
  overlay.querySelector(".cancel").addEventListener("click", close);
  overlay.querySelector(".confirm").addEventListener("click", () => { setSourceHidden(name, true); close(); });
  overlay.querySelector(".settings-link").addEventListener("click", () => {
    close();
    showView("settings");
    loadData();
    loadArchiveDates();
  });
}

document.addEventListener("click", (e) => {
  const btn = e.target.closest(".row-act.share");
  if (btn) {
    const li = btn.closest(".article");
    if (li) shareArticle(li, btn);
    // Don't keep focus on the button: :focus-within would otherwise hold the
    // row's white "card" state open after the pointer leaves.
    btn.blur();
    return;
  }
  // Eye-off next to the time asks to hide that source from the feed (#4). A
  // confirmation popup explains the action first, so an accidental click can't
  // silently make a source disappear.
  const hideBtn = e.target.closest(".hide-src");
  if (hideBtn) {
    const li = hideBtn.closest(".article");
    const srcEl = li && li.querySelector(".source");
    const name = srcEl ? srcEl.textContent.trim() : "";
    if (name) confirmHide(name);
    hideBtn.blur();
    return;
  }
  // Title link, "Open" and the source pill navigate on their own; just drop
  // focus so :focus-within doesn't leave the card stuck in its white state.
  const link = e.target.closest(".article a");
  if (link) {
    link.blur();
    return;
  }
  // Clicking anywhere else on the card opens the article in a new tab —
  // unless the user is selecting text.
  const sel = window.getSelection();
  if (sel && sel.toString()) return;
  const li = e.target.closest(".article");
  if (li) {
    const title = li.querySelector("a.title");
    if (title) window.open(title.href, "_blank", "noopener");
  }
});

window.addEventListener("hashchange", highlightFromHash);
highlightFromHash(); // honor an initial #hash on the server-rendered list
